version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  redis:
    image: "redis"
    restart: unless-stopped
    volumes:
      - cache:/data
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  cache:
  logs: