const mongoose = require("mongoose");

const questionSchema = new mongoose.Schema({
    // question _id generated by db
    creatorId: {type: String, required: true},
    title: {type: String, required: true}
});

const Question = mongoose.model("Question", questionSchema);

module.exports = {Question}